version: '3.8'

services:
  avito-backend-task-2023:
    build: ./
    command: ./wait-for-postgres.sh db ./avito-backend-task-2023
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=uthwtu

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=uthwtu
    ports:
      - 5432:5432