version: '3.8'

services:
  avito-backend-task-2023:
    build: ./
    command: ./wait-for-postgres.sh db ./avito-backend-task-2023
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db:
    restart: always
    image: postgres:latest
    volumes:
      - pg_data_volume:/data/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  pg_data_volume:
